# Generated by Django 2.2.24 on 2021-12-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submited', models.CharField(blank=True, max_length=50, null=True, verbose_name='تعداد ثبت نام شده')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=150, null=True, verbose_name='نام و نام خانوادگی')),
                ('course', models.CharField(blank=True, max_length=100, null=True, verbose_name='رشته')),
                ('uniid', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='کد دانشجویی')),
                ('entered', models.CharField(blank=True, max_length=50, null=True, verbose_name='سال ورود')),
                ('mobile', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شماره موبایل')),
                ('invitecode', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد دعوت')),
                ('submited', models.CharField(blank=True, max_length=50, null=True, verbose_name='تعداد ثبت نام شده')),
                ('create_at', models.DateTimeField(auto_now=True, null=True, verbose_name='زمان ثبت نام')),
                ('bed', models.CharField(blank=True, max_length=50, null=True, verbose_name='خوابگاهی؟')),
            ],
        ),
    ]
